@startuml
actor Visiteur
actor Client
actor Administrateur

Visiteur --> (Consulter les produits)
Visiteur --> (Rechercher un produit)
Visiteur --> (Consulter les avis)

Client --> (Créer un compte)
Client --> (Gérer son compte)
Client --> (Ajouter un produit au panier)
Client --> (Passer une commande)
Client --> (Suivre une commande)
Client --> (Laisser un avis)

Administrateur --> (Gérer les produits)
Administrateur --> (Gérer les commandes)
Administrateur --> (Consulter les statistiques de ventes)

@enduml
